name: App Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened]

jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      - uses: renzizza/ai-review_pr@main
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          github-token: ${{ secrets.GH_TOKEN }}
          github-pr-id: ${{ github.event.number }}
          dev-lang: Python
          openai-max-tokens: 4096
